name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --maxfail=5 --disable-warnings

      - name: Deploy with Gunicorn
        run: gunicorn app:app --bind 0.0.0.0:$PORT &

      - name: Stop Gunicorn
        run: pkill -f "gunicorn"

