name: Deploy API

on:
  push:
    branches:
      - main  # Déclencher le workflow sur les modifications de la branche "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configurer Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Étape 4 : Exécuter les tests unitaires
      - name: Run tests
        run: pytest --maxfail=5 --disable-warnings
        continue-on-error: true  # Ne pas bloquer le déploiement si les tests échouent

      # Étape 5 : Déployer sur Render
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-ct2gq668ii6s7393ob2g/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"clearCache":true}'

