name: Deploy API

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les push vers la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configurer Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Étape 4 : Exécuter les tests unitaires
      - name: Run tests
        run: pytest --maxfail=5 --disable-warnings
        continue-on-error: true  # Continue même si des tests échouent

      # Étape 5 : Déployer sur Render
      - name: Deploy to Render
        uses: jorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true  # Attend la fin du déploiement avant de passer à l'étape suivante

