{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "0c75c419-906b-4daf-bd4a-5d45d6dcdf73",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in /Applications/anaconda3/lib/python3.12/site-packages (1.37.1)\n",
      "Requirement already satisfied: altair<6,>=4.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (5.0.1)\n",
      "Requirement already satisfied: blinker<2,>=1.0.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (1.6.2)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (5.3.3)\n",
      "Requirement already satisfied: click<9,>=7.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (8.1.7)\n",
      "Requirement already satisfied: numpy<3,>=1.20 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (1.26.4)\n",
      "Requirement already satisfied: packaging<25,>=20 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (24.1)\n",
      "Requirement already satisfied: pandas<3,>=1.3.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (2.2.2)\n",
      "Requirement already satisfied: pillow<11,>=7.1.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (10.4.0)\n",
      "Requirement already satisfied: protobuf<6,>=3.20 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (4.25.3)\n",
      "Requirement already satisfied: pyarrow>=7.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (16.1.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (2.32.3)\n",
      "Requirement already satisfied: rich<14,>=10.14.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (13.7.1)\n",
      "Requirement already satisfied: tenacity<9,>=8.1.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (8.2.3)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.3.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (4.11.0)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (3.1.43)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (0.8.0)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (6.4.1)\n",
      "Requirement already satisfied: jinja2 in /Applications/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (3.1.4)\n",
      "Requirement already satisfied: jsonschema>=3.0 in /Applications/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
      "Requirement already satisfied: toolz in /Applications/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (0.12.0)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in /Applications/anaconda3/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /Applications/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Applications/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /Applications/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Applications/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Applications/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/Nelly/.local/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (1.26.20)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Applications/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /Applications/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Applications/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in /Applications/anaconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)\n",
      "Requirement already satisfied: mdurl~=0.1 in /Applications/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)\n",
      "Requirement already satisfied: six>=1.5 in /Applications/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)\n",
      "Collecting streamlit_jupyter\n",
      "  Downloading streamlit_jupyter-0.2.1-py3-none-any.whl.metadata (8.1 kB)\n",
      "Collecting fastcore (from streamlit_jupyter)\n",
      "  Downloading fastcore-1.7.20-py3-none-any.whl.metadata (3.5 kB)\n",
      "Collecting ipywidgets==7.7.2 (from streamlit_jupyter)\n",
      "  Downloading ipywidgets-7.7.2-py2.py3-none-any.whl.metadata (1.9 kB)\n",
      "Requirement already satisfied: jupyter in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit_jupyter) (1.0.0)\n",
      "Collecting stqdm (from streamlit_jupyter)\n",
      "  Downloading stqdm-0.0.5-py3-none-any.whl.metadata (3.0 kB)\n",
      "Requirement already satisfied: streamlit>=1.19 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit_jupyter) (1.37.1)\n",
      "Requirement already satisfied: tabulate in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit_jupyter) (0.9.0)\n",
      "Requirement already satisfied: tqdm in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit_jupyter) (4.66.5)\n",
      "Requirement already satisfied: ipykernel>=4.5.1 in /Applications/anaconda3/lib/python3.12/site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (6.28.0)\n",
      "Requirement already satisfied: ipython-genutils~=0.2.0 in /Applications/anaconda3/lib/python3.12/site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (0.2.0)\n",
      "Requirement already satisfied: traitlets>=4.3.1 in /Applications/anaconda3/lib/python3.12/site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (5.14.3)\n",
      "Requirement already satisfied: widgetsnbextension~=3.6.0 in /Applications/anaconda3/lib/python3.12/site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (3.6.6)\n",
      "Requirement already satisfied: ipython>=4.0.0 in /Applications/anaconda3/lib/python3.12/site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (8.27.0)\n",
      "Requirement already satisfied: jupyterlab-widgets<3,>=1.0.0 in /Applications/anaconda3/lib/python3.12/site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (1.0.0)\n",
      "Requirement already satisfied: altair<6,>=4.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (5.0.1)\n",
      "Requirement already satisfied: blinker<2,>=1.0.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (1.6.2)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (5.3.3)\n",
      "Requirement already satisfied: click<9,>=7.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (8.1.7)\n",
      "Requirement already satisfied: numpy<3,>=1.20 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (1.26.4)\n",
      "Requirement already satisfied: packaging<25,>=20 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (24.1)\n",
      "Requirement already satisfied: pandas<3,>=1.3.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (2.2.2)\n",
      "Requirement already satisfied: pillow<11,>=7.1.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (10.4.0)\n",
      "Requirement already satisfied: protobuf<6,>=3.20 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (4.25.3)\n",
      "Requirement already satisfied: pyarrow>=7.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (16.1.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (2.32.3)\n",
      "Requirement already satisfied: rich<14,>=10.14.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (13.7.1)\n",
      "Requirement already satisfied: tenacity<9,>=8.1.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (8.2.3)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.3.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (4.11.0)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (3.1.43)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (0.8.0)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit>=1.19->streamlit_jupyter) (6.4.1)\n",
      "Requirement already satisfied: notebook in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter->streamlit_jupyter) (7.2.2)\n",
      "Requirement already satisfied: qtconsole in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter->streamlit_jupyter) (5.5.1)\n",
      "Requirement already satisfied: jupyter-console in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter->streamlit_jupyter) (6.6.3)\n",
      "Requirement already satisfied: nbconvert in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter->streamlit_jupyter) (7.16.4)\n",
      "Requirement already satisfied: jinja2 in /Applications/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (3.1.4)\n",
      "Requirement already satisfied: jsonschema>=3.0 in /Applications/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (4.23.0)\n",
      "Requirement already satisfied: toolz in /Applications/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (0.12.0)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in /Applications/anaconda3/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.19->streamlit_jupyter) (4.0.7)\n",
      "Requirement already satisfied: appnope in /Applications/anaconda3/lib/python3.12/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (0.1.3)\n",
      "Requirement already satisfied: comm>=0.1.1 in /Applications/anaconda3/lib/python3.12/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (0.2.1)\n",
      "Requirement already satisfied: debugpy>=1.6.5 in /Applications/anaconda3/lib/python3.12/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (1.6.7)\n",
      "Requirement already satisfied: jupyter-client>=6.1.12 in /Applications/anaconda3/lib/python3.12/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (8.6.0)\n",
      "Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Applications/anaconda3/lib/python3.12/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (5.7.2)\n",
      "Requirement already satisfied: matplotlib-inline>=0.1 in /Applications/anaconda3/lib/python3.12/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (0.1.6)\n",
      "Requirement already satisfied: nest-asyncio in /Applications/anaconda3/lib/python3.12/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (1.6.0)\n",
      "Requirement already satisfied: psutil in /Applications/anaconda3/lib/python3.12/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (5.9.0)\n",
      "Requirement already satisfied: pyzmq>=24 in /Applications/anaconda3/lib/python3.12/site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (25.1.2)\n",
      "Requirement already satisfied: decorator in /Applications/anaconda3/lib/python3.12/site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (5.1.1)\n",
      "Requirement already satisfied: jedi>=0.16 in /Applications/anaconda3/lib/python3.12/site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.19.1)\n",
      "Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Applications/anaconda3/lib/python3.12/site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (3.0.43)\n",
      "Requirement already satisfied: pygments>=2.4.0 in /Applications/anaconda3/lib/python3.12/site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (2.15.1)\n",
      "Requirement already satisfied: stack-data in /Applications/anaconda3/lib/python3.12/site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.2.0)\n",
      "Requirement already satisfied: pexpect>4.3 in /Applications/anaconda3/lib/python3.12/site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (4.8.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /Applications/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit>=1.19->streamlit_jupyter) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Applications/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit>=1.19->streamlit_jupyter) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /Applications/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit>=1.19->streamlit_jupyter) (2023.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Applications/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit>=1.19->streamlit_jupyter) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Applications/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit>=1.19->streamlit_jupyter) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/Nelly/.local/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit>=1.19->streamlit_jupyter) (1.26.20)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Applications/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit>=1.19->streamlit_jupyter) (2024.8.30)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /Applications/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit>=1.19->streamlit_jupyter) (2.2.0)\n",
      "Requirement already satisfied: jupyter-server<3,>=2.4.0 in /Applications/anaconda3/lib/python3.12/site-packages (from notebook->jupyter->streamlit_jupyter) (2.14.1)\n",
      "Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in /Applications/anaconda3/lib/python3.12/site-packages (from notebook->jupyter->streamlit_jupyter) (2.27.3)\n",
      "Requirement already satisfied: jupyterlab<4.3,>=4.2.0 in /Applications/anaconda3/lib/python3.12/site-packages (from notebook->jupyter->streamlit_jupyter) (4.2.5)\n",
      "Requirement already satisfied: notebook-shim<0.3,>=0.2 in /Applications/anaconda3/lib/python3.12/site-packages (from notebook->jupyter->streamlit_jupyter) (0.2.3)\n",
      "Requirement already satisfied: beautifulsoup4 in /Applications/anaconda3/lib/python3.12/site-packages (from nbconvert->jupyter->streamlit_jupyter) (4.12.3)\n",
      "Requirement already satisfied: bleach!=5.0.0 in /Applications/anaconda3/lib/python3.12/site-packages (from nbconvert->jupyter->streamlit_jupyter) (4.1.0)\n",
      "Requirement already satisfied: defusedxml in /Applications/anaconda3/lib/python3.12/site-packages (from nbconvert->jupyter->streamlit_jupyter) (0.7.1)\n",
      "Requirement already satisfied: jupyterlab-pygments in /Applications/anaconda3/lib/python3.12/site-packages (from nbconvert->jupyter->streamlit_jupyter) (0.1.2)\n",
      "Requirement already satisfied: markupsafe>=2.0 in /Applications/anaconda3/lib/python3.12/site-packages (from nbconvert->jupyter->streamlit_jupyter) (2.1.3)\n",
      "Requirement already satisfied: mistune<4,>=2.0.3 in /Applications/anaconda3/lib/python3.12/site-packages (from nbconvert->jupyter->streamlit_jupyter) (2.0.4)\n",
      "Requirement already satisfied: nbclient>=0.5.0 in /Applications/anaconda3/lib/python3.12/site-packages (from nbconvert->jupyter->streamlit_jupyter) (0.8.0)\n",
      "Requirement already satisfied: nbformat>=5.7 in /Applications/anaconda3/lib/python3.12/site-packages (from nbconvert->jupyter->streamlit_jupyter) (5.10.4)\n",
      "Requirement already satisfied: pandocfilters>=1.4.1 in /Applications/anaconda3/lib/python3.12/site-packages (from nbconvert->jupyter->streamlit_jupyter) (1.5.0)\n",
      "Requirement already satisfied: tinycss2 in /Applications/anaconda3/lib/python3.12/site-packages (from nbconvert->jupyter->streamlit_jupyter) (1.2.1)\n",
      "Requirement already satisfied: qtpy>=2.4.0 in /Applications/anaconda3/lib/python3.12/site-packages (from qtconsole->jupyter->streamlit_jupyter) (2.4.1)\n",
      "Requirement already satisfied: six>=1.9.0 in /Applications/anaconda3/lib/python3.12/site-packages (from bleach!=5.0.0->nbconvert->jupyter->streamlit_jupyter) (1.16.0)\n",
      "Requirement already satisfied: webencodings in /Applications/anaconda3/lib/python3.12/site-packages (from bleach!=5.0.0->nbconvert->jupyter->streamlit_jupyter) (0.5.1)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in /Applications/anaconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.19->streamlit_jupyter) (4.0.0)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.3 in /Applications/anaconda3/lib/python3.12/site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.8.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (23.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (0.10.6)\n",
      "Requirement already satisfied: platformdirs>=2.5 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (3.10.0)\n",
      "Requirement already satisfied: anyio>=3.1.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (4.2.0)\n",
      "Requirement already satisfied: argon2-cffi>=21.1 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (21.3.0)\n",
      "Requirement already satisfied: jupyter-events>=0.9.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.10.0)\n",
      "Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.4.4)\n",
      "Requirement already satisfied: overrides>=5.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (7.4.0)\n",
      "Requirement already satisfied: prometheus-client>=0.9 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.14.1)\n",
      "Requirement already satisfied: send2trash>=1.8.2 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.8.2)\n",
      "Requirement already satisfied: terminado>=0.8.3 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.17.1)\n",
      "Requirement already satisfied: websocket-client>=1.7 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.8.0)\n",
      "Requirement already satisfied: async-lru>=1.0.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter->streamlit_jupyter) (2.0.4)\n",
      "Requirement already satisfied: httpx>=0.25.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter->streamlit_jupyter) (0.27.0)\n",
      "Requirement already satisfied: jupyter-lsp>=2.0.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter->streamlit_jupyter) (2.2.0)\n",
      "Requirement already satisfied: setuptools>=40.1.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter->streamlit_jupyter) (75.1.0)\n",
      "Requirement already satisfied: babel>=2.10 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter->streamlit_jupyter) (2.11.0)\n",
      "Requirement already satisfied: json5>=0.9.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter->streamlit_jupyter) (0.9.6)\n",
      "Requirement already satisfied: mdurl~=0.1 in /Applications/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit>=1.19->streamlit_jupyter) (0.1.0)\n",
      "Requirement already satisfied: fastjsonschema>=2.15 in /Applications/anaconda3/lib/python3.12/site-packages (from nbformat>=5.7->nbconvert->jupyter->streamlit_jupyter) (2.16.2)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /Applications/anaconda3/lib/python3.12/site-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.7.0)\n",
      "Requirement already satisfied: wcwidth in /Users/Nelly/.local/lib/python3.12/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.2.13)\n",
      "Requirement already satisfied: soupsieve>1.2 in /Applications/anaconda3/lib/python3.12/site-packages (from beautifulsoup4->nbconvert->jupyter->streamlit_jupyter) (2.5)\n",
      "Requirement already satisfied: executing in /Applications/anaconda3/lib/python3.12/site-packages (from stack-data->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.8.3)\n",
      "Requirement already satisfied: asttokens in /Applications/anaconda3/lib/python3.12/site-packages (from stack-data->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (2.0.5)\n",
      "Requirement already satisfied: pure-eval in /Applications/anaconda3/lib/python3.12/site-packages (from stack-data->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.2.2)\n",
      "Requirement already satisfied: sniffio>=1.1 in /Applications/anaconda3/lib/python3.12/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.3.0)\n",
      "Requirement already satisfied: argon2-cffi-bindings in /Applications/anaconda3/lib/python3.12/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (21.2.0)\n",
      "Requirement already satisfied: httpcore==1.* in /Applications/anaconda3/lib/python3.12/site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook->jupyter->streamlit_jupyter) (1.0.2)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /Applications/anaconda3/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook->jupyter->streamlit_jupyter) (0.14.0)\n",
      "Requirement already satisfied: python-json-logger>=2.0.4 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (2.0.7)\n",
      "Requirement already satisfied: pyyaml>=5.3 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (6.0.1)\n",
      "Requirement already satisfied: rfc3339-validator in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.1.4)\n",
      "Requirement already satisfied: rfc3986-validator>=0.1.1 in /Applications/anaconda3/lib/python3.12/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.1.1)\n",
      "Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter)\n",
      "  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)\n",
      "Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter)\n",
      "  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)\n",
      "Requirement already satisfied: jsonpointer>1.13 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (2.1)\n",
      "Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter)\n",
      "  Using cached uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)\n",
      "Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter)\n",
      "  Using cached webcolors-24.11.1-py3-none-any.whl.metadata (2.2 kB)\n",
      "Requirement already satisfied: cffi>=1.0.1 in /Applications/anaconda3/lib/python3.12/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.17.1)\n",
      "Requirement already satisfied: pycparser in /Applications/anaconda3/lib/python3.12/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (2.21)\n",
      "Requirement already satisfied: arrow>=0.15.0 in /Applications/anaconda3/lib/python3.12/site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.2.3)\n",
      "Downloading streamlit_jupyter-0.2.1-py3-none-any.whl (13 kB)\n",
      "Downloading ipywidgets-7.7.2-py2.py3-none-any.whl (123 kB)\n",
      "Downloading fastcore-1.7.20-py3-none-any.whl (83 kB)\n",
      "Downloading stqdm-0.0.5-py3-none-any.whl (11 kB)\n",
      "Using cached webcolors-24.11.1-py3-none-any.whl (14 kB)\n",
      "Using cached fqdn-1.5.1-py3-none-any.whl (9.1 kB)\n",
      "Using cached isoduration-20.11.0-py3-none-any.whl (11 kB)\n",
      "Using cached uri_template-1.3.0-py3-none-any.whl (11 kB)\n",
      "Installing collected packages: webcolors, uri-template, fqdn, fastcore, isoduration, stqdm, ipywidgets, streamlit_jupyter\n",
      "  Attempting uninstall: ipywidgets\n",
      "    Found existing installation: ipywidgets 7.8.1\n",
      "    Uninstalling ipywidgets-7.8.1:\n",
      "      Successfully uninstalled ipywidgets-7.8.1\n",
      "Successfully installed fastcore-1.7.20 fqdn-1.5.1 ipywidgets-7.7.2 isoduration-20.11.0 stqdm-0.0.5 streamlit_jupyter-0.2.1 uri-template-1.3.0 webcolors-24.11.1\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit\n",
    "!pip install streamlit_jupyter"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "7056a21b-2d90-484d-95c2-133371ac767c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-11-26 21:35:09.400 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run /opt/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import requests\n",
    "import pandas as pd\n",
    "\n",
    "# Définir l'URL de l'API déployée\n",
    "API_URL = \"https://projet7-gszq.onrender.com/predict\"  # Remplacez par l'URL de votre API\n",
    "\n",
    "# Titre\n",
    "st.title(\"Dashboard de Prédiction des Risques - Dimension Métier\")\n",
    "\n",
    "# Description\n",
    "st.markdown(\"\"\"\n",
    "Ce tableau de bord permet de :\n",
    "1. Tester des scénarios de crédit avec l'API.\n",
    "2. Optimiser le seuil métier pour minimiser les coûts des erreurs (FN et FP).\n",
    "3. Comparer les coûts métiers pour différents seuils.\n",
    "\"\"\")\n",
    "\n",
    "# Entrée des paramètres utilisateur\n",
    "st.sidebar.header(\"Paramètres d'entrée\")\n",
    "CODE_GENDER = st.sidebar.selectbox(\"Genre (0=Femme, 1=Homme)\", [0, 1])\n",
    "FLAG_OWN_CAR = st.sidebar.selectbox(\"Possède une voiture (0=Non, 1=Oui)\", [0, 1])\n",
    "CNT_CHILDREN = st.sidebar.slider(\"Nombre d'enfants\", 0, 10, 2)\n",
    "AMT_INCOME_TOTAL = st.sidebar.number_input(\"Revenu total annuel\", min_value=0, step=1000, value=202500)\n",
    "AMT_CREDIT = st.sidebar.number_input(\"Montant du crédit demandé\", min_value=0, step=1000, value=500000)\n",
    "AMT_ANNUITY = st.sidebar.number_input(\"Montant de l'annuité\", min_value=0, step=100, value=25000)\n",
    "AMT_GOODS_PRICE = st.sidebar.number_input(\"Prix des biens\", min_value=0, step=1000, value=450000)\n",
    "\n",
    "# Coût des erreurs métier\n",
    "st.sidebar.header(\"Paramètres métier\")\n",
    "FN_COST = st.sidebar.number_input(\"Coût d'un faux négatif (FN)\", min_value=1, value=10)\n",
    "FP_COST = st.sidebar.number_input(\"Coût d'un faux positif (FP)\", min_value=1, value=1)\n",
    "\n",
    "# Seuil de décision (par défaut : seuil optimal calculé)\n",
    "st.sidebar.markdown(f\"**Seuil optimal calculé : 0.09**\")\n",
    "threshold = st.sidebar.slider(\"Seuil de décision (probabilité)\", 0.0, 1.0, 0.09, 0.01)\n",
    "\n",
    "# Création du dataset\n",
    "data = [\n",
    "    {\n",
    "        \"CODE_GENDER\": CODE_GENDER,\n",
    "        \"FLAG_OWN_CAR\": FLAG_OWN_CAR,\n",
    "        \"CNT_CHILDREN\": CNT_CHILDREN,\n",
    "        \"AMT_INCOME_TOTAL\": AMT_INCOME_TOTAL,\n",
    "        \"AMT_CREDIT\": AMT_CREDIT,\n",
    "        \"AMT_ANNUITY\": AMT_ANNUITY,\n",
    "        \"AMT_GOODS_PRICE\": AMT_GOODS_PRICE,\n",
    "    }\n",
    "]\n",
    "\n",
    "st.write(\"Données envoyées à l'API :\")\n",
    "st.json(data)\n",
    "\n",
    "# Bouton pour envoyer les données\n",
    "if st.button(\"Envoyer et calculer les décisions métier\"):\n",
    "    try:\n",
    "        # Appel de l'API\n",
    "        response = requests.post(API_URL, json=data)\n",
    "        if response.status_code == 200:\n",
    "            predictions = response.json().get(\"predictions\", [])\n",
    "            st.success(\"Prédictions reçues avec succès !\")\n",
    "            st.write(\"Probabilités :\", predictions)\n",
    "\n",
    "            # Calcul des décisions métier\n",
    "            decisions = [\"Accepté\" if p >= threshold else \"Refusé\" for p in predictions]\n",
    "            st.write(\"Décisions métier :\", decisions)\n",
    "\n",
    "            # Calcul des coûts métier\n",
    "            costs = [\n",
    "                FN_COST if (d == \"Accepté\" and p < threshold) else FP_COST\n",
    "                for p, d in zip(predictions, decisions)\n",
    "            ]\n",
    "            total_cost = sum(costs)\n",
    "            st.write(f\"Coût métier total (pour le seuil {threshold}) : {total_cost}\")\n",
    "\n",
    "            # Comparer les coûts pour différents seuils\n",
    "            st.subheader(\"Comparaison des coûts pour différents seuils\")\n",
    "            for test_threshold in [0.05, 0.09, 0.5]:\n",
    "                test_decisions = [\"Accepté\" if p >= test_threshold else \"Refusé\" for p in predictions]\n",
    "                test_costs = [\n",
    "                    FN_COST if (d == \"Accepté\" and p < test_threshold) else FP_COST\n",
    "                    for p, d in zip(predictions, test_decisions)\n",
    "                ]\n",
    "                test_total_cost = sum(test_costs)\n",
    "                st.write(f\"Seuil {test_threshold:.2f} : Coût métier total = {test_total_cost}\")\n",
    "\n",
    "        else:\n",
    "            st.error(f\"Erreur API : {response.status_code}\")\n",
    "            st.write(response.text)\n",
    "\n",
    "    except Exception as e:\n",
    "        st.error(f\"Erreur : {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "204cf3c6-d805-4de2-aeb6-621bb5f1065b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
