channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=24.3.1
- pip:
  - mlflow==2.17.1
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.24.4
  - pandas==1.5.3
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.5.2
  - scipy==1.10.1
name: mlflow-env
