name: Déploiement API et Frontend

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les push vers la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Vérification du code
        uses: actions/checkout@v2

      - name: Configuration Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Télécharger clients_data.csv depuis Google Drive
        run: |
          pip install gdown
          gdown https://drive.google.com/uc?id=1KtMJY_PQy5EdE_qrfr7NN2_1cP10o0aQ -O clients_data.csv
          mv clients_data.csv backend/

      - name: Exécuter les tests unitaires
        run: pytest --maxfail=5 --disable-warnings

      - name: Assurer que les fichiers backend sont présents
        run: |
          if [ ! -f backend/best_model_lgb_no.pkl ]; then
            echo "Fichier best_model_lgb_no.pkl introuvable dans le dossier backend !"
            exit 1
          fi
          if [ ! -f backend/clients_data.csv ]; then
            echo "Fichier clients_data.csv introuvable dans le dossier backend !"
            exit 1
          fi

      # Déploiement du backend
      - name: Lancer le Backend sur Render
        uses: jorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true

      # Déploiement du frontend
      - name: Lancer le Frontend sur Render
        uses: jorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true

