name: Déploiement et tests unitaires

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Configurer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Installer les dépendances
      run: pip install -r requirements.txt

    - name: Exécuter les tests unitaires
      run: pytest

    - name: Lancer l'API 
      run: python app.py
